#13 Support Jakarta EE 10
prolutionsGmbH/herasaf-xacml-core pull request #14
Opened 2023-07-07 16:26 UTC by Thopap

* Update to java 11
* switch to jakarta xml bind
* some dependency updates

BREAKING CHANGE: Java 11 is now required and J2EE 10

2023-07-10 06:25 UTC, fhuonder requested changes
Please rewrite the commit message to the semver pattern. Use the key "breaking" to trigger a new major version on releasing.

Example:
breaking: support jakarta EE10

2023-07-10 06:25 UTC, fhuonder commented on src/main/java/org/herasaf/xacml/core/types/Time.java
> +			logger.error("Parsing time is not supported.");
The string is duplicated now. Please revert this change to use the variable.

2023-07-10 09:21 UTC, fhuonder commented
> > Please rewrite the commit message to the semver pattern. Use the key "breaking" to trigger a new major version on releasing.
> > Example: breaking: support jakarta EE10
> 
> I had followed the description in https://github.com/semantic-release/semantic-release for the commit message, where the label was "BREAKING CHANGE". If i understand the definition correctly, the "BREAKING CHANGE: " prefix must be part of the commit headline instead of the footer that i have choosen, correct?

Yes, it must be part of the headline. See here: https://github.com/prolutionsGmbH/herasaf-xacml-core/blob/main/ci/GitVersion.yml
Can be "breaking:" or "BREAKING CHANGE:"

2023-07-12 05:23 UTC, Thopap commented on src/main/java/org/herasaf/xacml/core/types/Time.java
> +			logger.error("Parsing time is not supported.");
String duplicate was removed again and a small improvement was added in the message.

2023-07-12 05:28 UTC, fhuonder requested changes
Looks good. Could you please rename the commit headline to
BREAKING CHANGE: support Jakarta EE 10 (#13)

Then I can approve the pr and create a release.

2023-07-13 07:43 UTC, fhuonder approved these changes

2023-07-13 07:43 UTC, merged